source('initialize.R')
install.packages('googleVis')
.Platform
.Platform$OS.type
source('initialize.R')
source('initialize.R')
library(R2wd)
wdGet()
install.packages('rcom')
install.packages('RDCOMClient')
wdGet()
install.packages('rcom')
install.packages("C:/Users/Mithu/Downloads/rcom_2.3-1.zip", repos = NULL)
search()
detach()
detach()
library(R2wd)
wdGet()
?wdGet
wdTitle("Testing")
wdEqn("\\alpha \\over ( \\beta + 3 )")
wdQuit()
wdGet()
wdTitle("Test")
wdSave()
wdSave()
wdBody("This is a test of this sytem")
wdUndo)()
wdUndo()
wdBody("This is a test of this system")
data(mtcars)
names(mtcars)
lm(mpg~cyl+disp+hp+wt+vs+am, data=mtcars)
m1=lm(mpg~cyl+disp+hp+wt+vs+am, data=mtcars)
summary(m1)
wdTable(summary(m1))
wdTable(summary(m1)$coef)
wdTable(summary(m1)$coef,digits=2)
?wdTable
wdTable(round(summary(m1)$coef,2), caption='Linear model')
format(mtcars)
mtcars
?format
source('D:/Teaching/RBasic2/initialize.R')
getwd()
source('C:/Users/Mithu/Dropbox/teaching/DC2/RBasic2/initialize.R')
search()
library(devtools)
find_rtools()
find_rtools()
library(devtools)
find_rtools()
remove.packages('devtools')
search()
detach()
install.packages('devtools')
install.packages("devtools")
install.packages("devtools")
library(devtools)
find_rtools()
find_rtools
library(devtools)
source('C:/Users/Mithu/Dropbox/teaching/DC2/RBasic2/initialize.R')
source('C:/Users/Mithu/Dropbox/teaching/DC2/RBasic2/initialize.R')
search()
source('C:/Users/Mithu/Dropbox/teaching/DC2/RBasic2/initialize.R')
library(randomForest)
install.packages('randomForest')
library(randomForest)
source('initialize.R')
library(slidify)
slidify('index.Rmd')
slidify('index.Rmd')
slidify('index.Rmd')
slidify('index.Rmd')
slidify('index.Rmd')
slidify('index.Rmd')
slidify('index.Rmd')
slidify('index.Rmd')
slidify('index.Rmd')
library(xtable)
X <- matrix("",ncol=2,nrow=2)
X[,1] <- c('E-mail','Twitter')
X[,2] <- c('abhijit@datacommunitydc.org','@webbedfeet')
X
xtable(X)
print(xtable(X),type='html')
slidify('index.Rmd')
slidify('index.Rmd')
slidify('index.Rmd')
?xtable
slidify('index.Rmd')
getOption('xtable.html.table.attributes')
getOption('xtable.html.table.attributes')
slidify('index.Rmd')
slidify('index.Rmd')
slidify('index.Rmd')
slidify('index.Rmd')
slidify('index.Rmd')
slidify('index.Rmd')
slidify('index.Rmd')
slidify('index.Rmd')
slidify('index.Rmd')
slidify('index.Rmd')
slidify('index.Rmd')
args(read.table)
slidify('index.Rmd')
slidify('index.Rmd')
slidify('index.Rmd')
slidify('index.Rmd')
slidify('index.Rmd')
slidify('index.Rmd')
slidify('index.Rmd')
slidify('index.Rmd')
slidify('index.Rmd')
slidify('index.Rmd')
slidify('index.Rmd')
args(head)
?head
?head
slidify('index.Rmd')
library(RODBC)
con = odbcConnect(MCT4)
con = odbcConnect('MCT4')
sqlTables(con)
sqlFetch(con, 'Sheet1')
bl=sqlFetch(con, 'Sheet1')
head(bl)
dim(bl)
head(bl[,1:4])
slidify('index.Rmd')
?sqlFetch
odbcDataSources()
slidify('index.Rmd')
slidify('index.Rmd')
slidify('index.Rmd')
?readLines
con <- odbcConnect('MCT4')
readLines(con)
odbcClose(con)
BP <- readLines('data/bpdata.csv)
ls()
history()
?history
cars <- read.table('data/Cars.txt')
View(cars)
View(cars)
str(cars)
cars <- read.table('data/Cars.txt', stringsAsFactors=F)
str(cars)
cars$V4
head(cars)
is.matrix(cars)
is.list(cars)
cars[,c('V2','V4','V6')]
head(cars[,c('V2','V4','V6')])
head(cars[,paste0('V',2:5)])
cars$V4
cars$V4[cars$V4=='?'] <- NA
cars$V4
is.null(cars$V4)
is.na(cars$V4)
cars$V4 <- as.numeric(cars$V4)
cars$V4
str(cars)
summary(cars)
library(Hmisc)
describe(cars)
data()
data(mtcars)
mtcars <- transform(mtcars, kmpg=mpg*1.6)
head(mtcars)
rm(mtcars)
data(mtcars)
head(mtcars)
mtcars = mutate(mtcars, kmpg=mpg*1.6, kml=kmpg/3.8)
library(plyr)
mtcars = mutate(mtcars, kmpg=mpg*1.6, kml=kmpg/3.8)
head(mtcars)
x <- list()
x[[1]] <- 1:10
x[[2]] <- c('Sam','Joe','Ted')
x[[3]] <- runif(25)
x
lapply(x, sort)
library(reshape2)
?reshape
?melt
airquality
head(airquality)
aq2 <- melt(airquality, id=c('Month','Day'))
head(aq2)
library(plyr)
summ <- ddply(mtcars, ~cyl, summarise, mean.mpg = mean(mpg))
summ
models=dlply(mtcars, ~cyl, function(m) lm(mpg~disp+hp, data=m))
models
lapply(models, summary)
summ <- ddply(mtcars, ~cyl, summarise, mean.mpg = mean(mpg))
sqldf('select cyl, avg(mpg) from mtcars group by cyl')
library(sqldf)
sqldf('select cyl, avg(mpg) from mtcars group by cyl')
summ
library(data.table)
DT <- data.table(mtcars)
print(DT[,mean(mpg), by=cyl])
library(slidify)
slidify('index.Rmd')
BP <- read.table('data/bpdata.csv', header=T, sep=',')
head(BP)
index <- sample.int(nrow(BP),200, replace=F)
newBP <- BP[index,]
sample(c('apple','pear','banana','guava','kiwi','pomegranate'), 3)
sample(c('apple','pear','banana','guava','kiwi','pomegranate'), 3)
sample(c('apple','pear','banana','guava','kiwi','pomegranate'), 3)
set.seed(124)
sample(c('apple','pear','banana','guava','kiwi','pomegranate'), 3)
set.seed(124)
sample(c('apple','pear','banana','guava','kiwi','pomegranate'), 3)
geno = read.csv('data/geno.csv')
pheno=read.csv('data/pheno.csv')
head(geno)
head(pheno)
fulldata <- merge(pheno, geno, by.x='id', by.y='id', all.x=T, all.y=T)
head(fulldata)
join
?join
names(fulldata)
names(fulldata)[3] <- 'gender'
names(fulldata)
names(fulldata) <- tolower(names(fulldata))
library(stringr)
newcar <- readLines('data/Car.txt')
newcar <- readLines('data/Cars.txt')
newcar[1]
str_split(newcar[1], ' ')
str_split(newcar[1], [ ]+)
str_split(newcar[1], '[ ]+')
library(ggplot2)
head(diamonds)
?ggplot
nrow(diamonds)
newdiamonds <- diamonds[sample.int(nrow(diamonds), 1000, replace=F),]
dim(newdiamonds)
plt <- ggplot(newdiamonds, aes(x=carat, y=price))
plt + geom_point()
plt <- ggplot(newdiamonds, aes(x=carat, y=price, group=clarity, color=clarity))
plt + geom_point()
plt + geom_point()+facet_grid(~cut)
plt + geom_point()+facet_grid(~cut, nrow=2)
plt + geom_point()+facet_wrap(~cut, nrow=2)
plt + geom_point()+facet_wrap(~cut)
plt + geom_point()+geom_smooth()+facet_wrap(~cut)
plt + geom_point()+geom_smooth()
mod1 = lm(mpg~cyl+hp+disp, data=mtcars)
summary(mod1)
names(summary(mod1))
summary(mod1)$coef
is.data.frame(summary(mod1)$coef)
as.data.frame(summary(mod1)$coef)
coefs = as.data.frame(summary(mod1)$coef)
coefs
names(coefs)
names(coefs) <- c('Estimate','SE','T','pval')
names(coefs)
coefs
coefs = transform(coefs, lcb = Estimate - 2*SE, ucb = Estimate+2*SE)
coefs
plt = ggplot(coefs[-1, aes(x=1:3, y = Estimate, ymin=lcb, ymax=ucb))
plt = ggplot(coefs[-1,], aes(x=1:3, y = Estimate, ymin=lcb, ymax=ucb))
plt+geom_pointrange()
plt = ggplot(coefs[3:4,], aes(x=1:3, y = Estimate, ymin=lcb, ymax=ucb))
plt+geom_pointrange()
plt = ggplot(coefs[-1,], aes(x=1:3, y = Estimate, ymin=lcb, ymax=ucb))
plt+geom_pointrange()
plt=plt+geom_pointrange()
pdf('test.pdf')
print(plt)
dev.off()
library(rCharts)
names(iris) = gsub("\\.", "", names(iris))
rPlot(SepalLength ~ SepalWidth | Species, data = iris, color = 'Species', type = 'point')
hair_eye_male <- subset(as.data.frame(HairEyeColor), Sex == "Male")
n1 <- nPlot(Freq ~ Hair, group = "Eye", data = hair_eye_male, type = "multiBarChart")
hair_eye_male
n1$print("chart3")
n1
require(reshape2)
uspexp <- melt(USPersonalExpenditure)
names(uspexp)[1:2] = c("category", "year")
x1 <- xPlot(value ~ year, group = "category", data = uspexp, type = "line-dotted")
head(USPersonalExpenditure)
head(uspexp)
x1
library(googleVis)
demo(WorldBank)
data(iris)
str(iris)
pairs(iris[,-5])
?dist
d <- dist(iris[,-5])
d
?hclust
hclust(d, method='average')
h=hclust(d, method='average')
plot(h)
abline(h=1.7)
summary(h)
?hclust
h1 = cutree(h)
h1 = cutree(h,3)
h1
cbind(h1, iris$Species)
cbind(h1, as.character(iris$Species))
data.frame(h1, as.character(iris$Species))
dat = data.frame(cluster=h1, species=as.character(iris$Species))
dlply(dat, ~species, table)
?kmeans
g = kmeans(iris[,-5],3)
g
g$cluster
dat = data.frame(species = as.character(iris$Species), hcl = h1, km=g$cluster)
head(dat)
dlply(dat, ~species, function(m) table(m$hcl, m$km))
dat2 = cbind(iris,hcl= h1, km=g$cluster)
ggplot(dat2, aes(x=Sepal.Length, y=Sepal.Width, group=hcl, color=hcl))+geom_point()
dat2 = cbind(iris,hcl= as.factor(h1), km=as.factor(g$cluster))
ggplot(dat2, aes(x=Sepal.Length, y=Sepal.Width, group=hcl, color=hcl))+geom_point()
ggplot(dat2, aes(x=Sepal.Length, y=Sepal.Width, group=Species, color=Species))+geom_point()
ggplot(dat2, aes(x=Sepal.Length, y=Sepal.Width, group=km, color=km))+geom_point()
?heatmap
x  <- as.matrix(mtcars)
rc <- rainbow(nrow(x), start = 0, end = .3)
cc <- rainbow(ncol(x), start = 0, end = .3)
hv <- heatmap(x, col = cm.colors(256), scale = "column",
RowSideColors = rc, ColSideColors = cc, margins = c(5,10),
xlab = "specification variables", ylab =  "Car Models",
main = "heatmap(<Mtcars data>, ..., scale = \"column\")")
?parallel
savehistory("~/Dropbox/teaching/DC2/RBasic2/workshopReal.R")
